=== llgava/minecraft-bedrock-schemas/schemas/1.18.10/rp_terrain_texture.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/TerrainTextureSchema",
  "definitions": {
    "TerrainTextureSchema": {
      "type": "object",
      "properties": {
        "resource_pack_name": {
          "type": "string"
        },
        "texture_name": {
          "type": "string",
          "const": "atlas.terrain"
        },
        "num_mip_levels": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "number",
              "const": 4
            }
          ]
        },
        "padding": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "number",
              "const": 8
            }
          ]
        },
        "texture_data": {
          "$ref": "#/definitions/MinecraftTextureData"
        }
      },
      "required": [
        "resource_pack_name",
        "texture_name",
        "num_mip_levels",
        "padding",
        "texture_data"
      ],
      "additionalProperties": false,
      "$id": "llgava.resource_packs.TerrainTexture"
    },
    "MinecraftTextureData": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/MinecraftTextures"
      }
    },
    "MinecraftTextures": {
      "type": "object",
      "properties": {
        "textures": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "$ref": "#/definitions/Textures"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "Textures": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        },
        "overlay_color": {
          "type": "string",
          "pattern": "^#(?:[0-9a-fA-F]{3}){1,2}$"
        },
        "tint_color": {
          "type": "string",
          "pattern": "^#(?:[0-9a-fA-F]{3}){1,2}$"
        },
        "variations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Variations"
          }
        }
      },
      "additionalProperties": false
    },
    "Variations": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        },
        "weight": {
          "type": "number"
        }
      },
      "additionalProperties": false
    }
  }
}

=== llgava/minecraft-bedrock-schemas/playground/RP/textures/terrain_texture.json
{
  "resource_pack_name": "pack.name",
  "texture_name": "atlas.terrain",
  "num_mip_levels": 4,
  "padding": 8,
  "texture_data": {
    "single_example_block": {
      "textures": "textures/blocks/example_block"
    },

    "array_example_block": {
      "textures": [
        "textures/blocks/array_example_block_0",
        "textures/blocks/array_example_block_1",
        "textures/blocks/array_example_block_2"
      ]
    },

    "variantion_example_block": {
      "textures": {
        "path": "textures/blocks/variation_example_block",
        "tint_color": "#000",
        "overlay_color": "#FF00FF",
        "variations": [
          {
            "path": "textures/blocks/variation_example_block_0",
            "weight": 50
          },
          {
            "path": "textures/blocks/variation_example_block_1",
            "weight": 50
          }
        ]
      }
    }
  }
}
